name: ENV Variables

on: push

jobs:
  strategies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run_num: [1, 2, 3]
        another_var: [one, two]
        exclude:
          - run_num: 1
            another_var: one
          - run_num: 2
            another_var: two
    steps:
      - name: Strategy Run no.${{ matrix.run_num }}
        run: |
          echo "Run number is ${{ matrix.run_num }}"
